name: Run MATLAB Tests

on:
  pull_request:
    branches: 
      - 'main'
      - 'release-staging-*'
  push:
    branches: 
      - 'main'
      - 'release-staging-*'
  workflow_dispatch:
  
jobs:
  tests:
    name: MATLAB Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        matlab: ["R2022b"]
        os: [ubuntu-latest, windows-latest]
    env:
      MLM_LICENSE_FILE: ${{ secrets.MATLAB_LICENSE }}
    steps:
    - name: Check out repository
      uses: actions/checkout@main
    
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ matrix.matlab }}
        cache: true
    
    - name: Run tests
      uses: matlab-actions/run-tests@v2
      with:
         source-folder: 'onc'
      env:
        TOKEN: ${{ secrets.TOKEN }}
        ONC_ENV: 'prod'
    
